name: Validate JSON
on:
  push:

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate index.json
        run: jsonschema -i index.json index.schema.json
